name: Android CI

on: push

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build debug APK
        run: bash ./gradlew app:assembleDebug --stacktrace
      - name: upload apk
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: wanandroid-apk
          path: ${{ github.workspace }}/app/build/outputs/apk/debug